version: 2
project_name: "gitlab-stats"
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=1
    ldflags:
      - -X main.version={{.Version}}
    goos:
      - linux
      # - darwin
    goarch:
      - amd64
      # - arm
      # - arm64
    goarm:
      # - "6"
      - "7"
    dir: cmd/gitlab-stats
    id: lin

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    formats: ["binary"]

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'