# https://taskfile.dev
version: '3'
vars:
  BINFILE: gitlab-stats

dotenv: ['.env']

includes:
  dev: ./Taskfile_dev.yml

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task -a

  build:
    desc: "Build the binary"
    cmds:
      - go mod download
      - go generate ./...
      - CGO_ENABLED=1 go build -o gitlab-stats cmd/gitlab-stats/*go

  test:
    desc: "Run tests"
    # dir: gowork
    cmds:
      - test -d tests || mkdir tests
      - rm -f /tmp/db.json 
      - go run cmd/gendb4tests/*go -p 1
      - go run cmd/gitlab-stats/*go -p 1 -o tests/stats-project-1.png -db /tmp/db.json
      - go run cmd/gendb4tests/*go -g 10
      - go run cmd/gitlab-stats/*go -g 10 -o tests/stats-project-10.png -db /tmp/db.json

  snapshot:
    desc: "Create a snapshot"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    desc: "Create a release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean