# https://taskfile.dev
version: '3'
vars:
  BINFILE: gitlab-stats

tasks:
  default:
    cmds:
      - go mod download
      - CGO_ENABLED=0 go build .
      - upx ./{{.BINFILE}}
    # silent: true
    sources:
    - ./**/*
    method: checksum
    generates:
      - "{{.BINFILE}}"

  snapshot:
    cmds:
      - GITLAB_TOKEN="" goreleaser --rm-dist --snapshot
    
  release:
    cmds:
      - GITLAB_TOKEN="" goreleaser --rm-dist